baseURL = "https://lucasaguiar.xyz"
languageCode = "en-us"
title = "Lucas F. Aguiar"
themesDir = "themes"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Home"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
#  [languages.fr]
#    title = "Ananke Fr"
#    weight = 2
#    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Lucas F. Aguiar"
  favicon = "/favicons/favicon-32x32.png"
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[taxonomies]
category = "categories"
tag = "tags"


[[params.ananke_socials]]
#linkedin = "linkedin"
#linkedinurl = "https://linkedin.com/in/lucas-fernandes-aguiar"
#github = "github"
#githuburl = "https://github.com/isfttr"
name = "github"
url = "https://github.com/isfttr"

